fix "Argument skipDuplicates Does Not Exist On Enclosing Type" in create_many
Brendonovich/prisma-client-rust pull request #174
Opened 2022-10-11 10:25 UTC by Congyuwang

According to the hard-coded capabilities, the following two DB do not support skip_duplicates:
- mssql
- MongoDB

Therefore, remove skip_duplicates field whenever one of these two features is enabled.

2022-10-11 20:12 UTC, Brendonovich requested changes
To avoid having feature flags everywhere, they should only be present on the `skip_duplicates` function declaration and the relevant `selection.push_argument` call.
This will result in a couple bytes overhead since `skip_duplicates` will always be passed around but I'm willing to accept it if the code is made significantly simpler.

2022-10-12 01:23 UTC, Congyuwang commented on src/queries/create_many.rs
> +            #[cfg(not(any(feature = "mongodb", feature = "mssql")))]
```suggestion
```

2022-10-12 01:25 UTC, Congyuwang commented on src/queries/create_many.rs
> +        #[cfg(not(any(feature = "mongodb", feature = "mssql")))] skip_duplicates: bool,
```suggestion
        skip_duplicates: bool,
```

2022-10-12 01:26 UTC, Congyuwang commented on src/queries/create_many.rs
> +        #[cfg(not(any(feature = "mongodb", feature = "mssql")))]
```suggestion

```

2022-10-12 01:28 UTC, Congyuwang commented on src/queries/create_many.rs
> +        let mut selection = Self::to_selection(self.info.model, self.set_params);
```suggestion
```

2022-10-12 01:28 UTC, Congyuwang commented on src/queries/create_many.rs
> +
```suggestion
```

2022-10-12 04:07 UTC, Brendonovich approved these changes

2022-10-12 04:36 UTC, merged