added rocket example
Brendonovich/prisma-client-rust pull request #98
Opened 2022-07-08 22:28 UTC by aaronleopold

Hello again, feel free to close if you don't want this but I yoinked the guts from the Axum example I wrote to put together this barebones example using [Rocket](https://rocket.rs/) for #38

2022-07-08 23:24 UTC, Brendonovich requested changes
Thanks for this! I haven't used Rocket so I trust that this is how it's usually implemented 😅

2022-07-08 23:24 UTC, Brendonovich commented on examples/rocket/src/main.rs
> +    };
I think this is a nicer way to optionally extend the query.

```suggestion
    let mut query = ctx.db.user().find_many(vec![]);
    
    if load_posts.unwrap_or(true) {
        query = query.with(user::posts::fetch(vec![]));
    }
```

2022-07-08 23:55 UTC, aaronleopold commented
> Thanks for this! I haven't used Rocket so I trust that this is how it's usually implemented 😅

It's a pretty barebones template but it is the minimum required for a v0.5-rc Rocket app 😄 Rocket leans pretty hard on the macros

2022-07-09 00:00 UTC, Brendonovich approved these changes

2022-07-09 00:01 UTC, merged